#!/usr/bin/bash
#//Script Kiddies//
kiddies='\e[1;31m'
kiddes='\e[1;33m'
clear
echo ""
figlet " INSTAHACK " | lolcat
echo -e $kiddes "#####################"
echo "     # HANZELNUT # " | lolcat
echo "  # Hantu Team Cyber # " | lolcat
echo -e $kiddes "#####################"
echo -e $kiddies"==================================================="
python2 hackinsta.py;
fi
